### PR TITLE
fix(auth/keycloak): use external Keycloak URL for browser-facing OIDC endpoints

### LINKED ISSUE #110: SecurityPolicy generated for NebariApp uses in-cluster Keycloak URL for browser-facing endpoints (authorizationEndpoint, endSessionEndpoint)
## Symptom

When `nebari-operator` reconciles a `NebariApp` with `auth.provider: keycloak` + `auth.provisionClient: true`, it generates an Envoy Gateway `SecurityPolicy` with all four OIDC `provider` endpoints populated from the in-cluster Keycloak service URL:

```yaml
spec:
  oidc:
    clientID: <client>
    clientSecret: { ... }
    provider:
      authorizationEndpoint: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080/realms/nebari/protocol/openid-connect/auth
      endSessionEndpoint:    http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080/realms/nebari/protocol/openid-connect/logout
      issuer:                http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080/realms/nebari
      tokenEndpoint:         http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080/realms/nebari/protocol/openid-connect/token
    redirectURL: https://<app-host>/oauth2/callback
```

`authorizationEndpoint` and `endSessionEndpoint` are the URLs **the browser is redirected to**. The browser cannot resolve `keycloak-keycloakx-http.keycloak.svc.cluster.local`, so the entire OAuth2 login flow fails. Curl test:

```
$ curl -sS -i https://<app-host>/
HTTP/1.1 302 Found
location: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080/realms/nebari/protocol/openid-connect/auth?client_id=...
```

`tokenEndpoint` and `issuer` are server-to-server (Envoy proxy talking to Keycloak in-cluster); the in-cluster URL is fine for those.

## Expected

Operator already has both URLs in env:
- `KEYCLOAK_URL=http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080` (in-cluster)
- `KEYCLOAK_EXTERNAL_URL=https://keycloak.<base>` (public)

The SecurityPolicy generation should use:
- `authorizationEndpoint` and `endSessionEndpoint`: `KEYCLOAK_EXTERNAL_URL` (browser hits these)
- `tokenEndpoint` and `issuer`: either `KEYCLOAK_URL` (faster, in-cluster) or `KEYCLOAK_EXTERNAL_URL` (consistent). Both work; `KEYCLOAK_URL` is preferred for latency and to avoid making the public DNS / cert chain a hard dependency for token exchange.

## Reproduction

Clean NIC AWS deploy + a `NebariApp` with auth enabled. Reconcile completes, `SecurityPolicy` shows all four endpoints on the in-cluster URL. `curl -i https://<app-host>/` returns 302 with the in-cluster URL in `Location`.

## Where this surfaced

Validating the Nebari LLM Serving Pack fresh-install runbook (`nebari-dev/nebari-llm-serving-pack#65`) on a brand-new NIC + LLM-pack deploy. Blocks the user-facing key-manager UI flow end-to-end (the user is supposed to mint API keys from the UI; without working auth, no UI access).

## Operator version

`quay.io/nebari/nebari-operator:0.1.0-alpha.18`

## Suggested fix

In the SecurityPolicy templating code (wherever the four `provider.*` endpoints get rendered), split the URL source by endpoint:

```go
authorizationEndpoint := externalURL + "/realms/" + realm + "/protocol/openid-connect/auth"
endSessionEndpoint    := externalURL + "/realms/" + realm + "/protocol/openid-connect/logout"
issuer                := internalURL + "/realms/" + realm
tokenEndpoint         := internalURL + "/realms/" + realm + "/protocol/openid-connect/token"
```

If the codebase already has helpers for one URL, parameterize them with which env var to read. Existing `KEYCLOAK_EXTERNAL_URL` env should be the source for the two browser-facing endpoints; existing `KEYCLOAK_URL` for the two server-to-server endpoints.

### PR DESCRIPTION
**Pull request by dcmcand**
## Summary
- Split SecurityPolicy OIDC endpoint overrides by audience: Token stays on the in-cluster URL (Envoy back-channel), Authorization and EndSession move to the public URL (browser front-channel).
- Adds an `externalRealmURL()` helper mirroring `internalRealmURL()`.
- When `KEYCLOAK_EXTERNAL_URL` is unset, leaves Authorization/EndSession unset; Envoy Gateway then triggers OIDC discovery against the in-cluster issuer. Discovery only produces public URLs if Keycloak's own `frontendUrl` is configured. Operator now logs a startup warning so this trap is visible.
- Updated `TestKeycloakProvider_GetEndpointOverrides` with five cases covering the split, trailing-slash normalization, and the no-ExternalURL fallback.

## Why
On a clean NIC deploy, browsers hitting any NebariApp protected by Keycloak OAuth2 are redirected to `http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080` - which the browser cannot resolve. The OAuth2 flow dead-ends and no UI is reachable.

Surfaced during fresh-install validation of the Nebari LLM Serving Pack (nebari-dev/nebari-llm-serving-pack#65), which loads the key-manager UI as a NebariApp.

Closes #110

## Follow-ups (deliberately out of scope here)
- #112 - Should `SecurityPolicy.spec.oidc.provider.Issuer` also track `KEYCLOAK_EXTERNAL_URL` to match the `iss` claim in tokens issued by Keycloak with `frontendUrl` configured?
- #113 - Add a reconciler-level test asserting Token on in-cluster URL and Authorization+EndSession on public URL end-to-end through `buildSecurityPolicySpec`.

## Test plan
- [x] `go test ./internal/controller/reconcilers/auth/providers/...` passes - five cases covering the split, trailing-slash normalization, no-ExternalURL fallback
- [x] `go test ./...` no regressions vs main (pre-existing `TestControllers` HTTPRoute scheme failure unrelated)
- [x] `go build ./...` clean
- [ ] Validation against the llmd-validate cluster: build the operator image, swap it in via a temporary override on NIC's nebari-operator Application, confirm the rendered SecurityPolicy now uses `https://keycloak.<base>` for Authorization+EndSession, confirm browser login completes

### CODE REVIEW

File: internal/controller/reconcilers/auth/providers/keycloak.go [hunk 1]
```diff
@@ -59,22 +59,60 @@ func (p *KeycloakProvider) internalRealmURL() string {
...
+// or empty string when KEYCLOAK_EXTERNAL_URL is not configured.
+func (p *KeycloakProvider) externalRealmURL() string {
+	if p.Config.ExternalURL == "" {
+		return ""
+	}
+	return fmt.Sprintf("%s/realms/%s",
+		strings.TrimRight(p.Config.ExternalURL, "/"),
+		p.Config.Realm)
+}
+
```
Comment (marcelovilla) [inline internal/controller/reconcilers/auth/providers/keycloak.go:72]: Not a blocker but this seems to be the same URL being built by the `GetExternalIssuerURL` function:

https://github.com/nebari-dev/nebari-operator/blob/0d0a85b8003953eb7833d12892995ba20163bf14/internal/controller/reconcilers/auth/providers/keycloak.go#L118-L124

Not sure if it's intended because of the difference in handling the `p.Config.ExternalURL == ""` case but just flagging it in case it's not.

**Review by marcelovilla — APPROVED** [review]
Thanks for the PR @dcmcand. Just a small comment but approving nonetheless
